import Header from "@/app/Header/page";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { GlobalProvider } from "./GlobalProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./Providers";

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "A ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <GlobalProvider>
            <Header />
            {children}
            <Footer />
            <ToastContainer />
          </GlobalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
